name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-22.04

    name: Deploy to Cloudflare Workers
    steps:
      - uses: actions/checkout@main
      - name: Publish
        uses: cloudflare/wrangler-action@3.0.0

        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
